# Generated by Django 5.2.6 on 2025-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('medical_condition', models.TextField()),
                ('side_effects', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('drug_classes', models.TextField()),
                ('brand_names', models.TextField()),
                ('activity', models.TextField()),
                ('rx_otc', models.TextField()),
                ('pregnancy_category', models.CharField(max_length=10)),
                ('csa', models.TextField()),
                ('alcohol', models.TextField()),
                ('related_drugs', models.TextField()),
                ('medical_condition_description', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('no_of_reviews', models.IntegerField(blank=True, null=True)),
                ('drug_link', models.URLField()),
            ],
        ),
    ]
